package gd;
enum abstract MIDIMessage(cpp.UInt32) to cpp.UInt32 {
	final MIDI_MESSAGE_NONE = 0;
	final MIDI_MESSAGE_NOTE_OFF = 8;
	final MIDI_MESSAGE_NOTE_ON = 9;
	final MIDI_MESSAGE_AFTERTOUCH = 10;
	final MIDI_MESSAGE_CONTROL_CHANGE = 11;
	final MIDI_MESSAGE_PROGRAM_CHANGE = 12;
	final MIDI_MESSAGE_CHANNEL_PRESSURE = 13;
	final MIDI_MESSAGE_PITCH_BEND = 14;
	final MIDI_MESSAGE_SYSTEM_EXCLUSIVE = 240;
	final MIDI_MESSAGE_QUARTER_FRAME = 241;
	final MIDI_MESSAGE_SONG_POSITION_POINTER = 242;
	final MIDI_MESSAGE_SONG_SELECT = 243;
	final MIDI_MESSAGE_TUNE_REQUEST = 246;
	final MIDI_MESSAGE_TIMING_CLOCK = 248;
	final MIDI_MESSAGE_START = 250;
	final MIDI_MESSAGE_CONTINUE = 251;
	final MIDI_MESSAGE_STOP = 252;
	final MIDI_MESSAGE_ACTIVE_SENSING = 254;
	final MIDI_MESSAGE_SYSTEM_RESET = 255;
}