package gd;
extern class Node2D extends gd.CanvasItem {
	function set_position(p_position:gd.Vector2):Void;
	function set_rotation(p_radians:Float):Void;
	function set_rotation_degrees(p_degrees:Float):Void;
	function set_skew(p_radians:Float):Void;
	function set_scale(p_scale:gd.Vector2):Void;
	function get_position():gd.Vector2;
	function get_rotation():Float;
	function get_rotation_degrees():Float;
	function get_skew():Float;
	function get_scale():gd.Vector2;
	function rotate(p_radians:Float):Void;
	function move_local_x(p_delta:Float, ?p_scaled:Bool):Void;
	function move_local_y(p_delta:Float, ?p_scaled:Bool):Void;
	function translate(p_offset:gd.Vector2):Void;
	function global_translate(p_offset:gd.Vector2):Void;
	function apply_scale(p_ratio:gd.Vector2):Void;
	function set_global_position(p_position:gd.Vector2):Void;
	function get_global_position():gd.Vector2;
	function set_global_rotation(p_radians:Float):Void;
	function set_global_rotation_degrees(p_degrees:Float):Void;
	function get_global_rotation():Float;
	function get_global_rotation_degrees():Float;
	function set_global_skew(p_radians:Float):Void;
	function get_global_skew():Float;
	function set_global_scale(p_scale:gd.Vector2):Void;
	function get_global_scale():gd.Vector2;
	function look_at(p_point:gd.Vector2):Void;
	function get_angle_to(p_point:gd.Vector2):Float;
	function to_local(p_global_point:gd.Vector2):gd.Vector2;
	function to_global(p_local_point:gd.Vector2):gd.Vector2;
}