package gd;
extern class Object {
	function get_class():String;
	function is_class(p_class:String):Bool;
	function set(p_property:String, p_value:Dynamic):Void;
	function get(p_property:String):Dynamic;
	function set_indexed(p_property_path:String, p_value:Dynamic):Void;
	function get_indexed(p_property_path:String):Dynamic;
	function property_can_revert(p_property:String):Bool;
	function property_get_revert(p_property:String):Dynamic;
	function notification(p_what:Int, ?p_reversed:Bool):Void;
	function to_string():String;
	function get_instance_id():Int;
	function set_script(p_script:Dynamic):Void;
	function get_script():Dynamic;
	function set_meta(p_name:String, p_value:Dynamic):Void;
	function remove_meta(p_name:String):Void;
	function get_meta(p_name:String, ?p_default:Dynamic):Dynamic;
	function has_meta(p_name:String):Bool;
	function has_user_signal(p_signal:String):Bool;
	function remove_user_signal(p_signal:String):Void;
	function call(p_method:String):Dynamic;
	function call_deferred(p_method:String):Dynamic;
	function set_deferred(p_property:String, p_value:Dynamic):Void;
	function has_method(p_method:String):Bool;
	function get_method_argument_count(p_method:String):Int;
	function has_signal(p_signal:String):Bool;
	function set_block_signals(p_enable:Bool):Void;
	function is_blocking_signals():Bool;
	function notify_property_list_changed():Void;
	function set_message_translation(p_enable:Bool):Void;
	function can_translate_messages():Bool;
	function tr(p_message:String, ?p_context:String):String;
	function tr_n(p_message:String, p_plural_message:String, p_n:Int, ?p_context:String):String;
	function is_queued_for_deletion():Bool;
	function cancel_free():Void;
}