<xml>
	<files id="__lib__">
		<compilerflag value="-I${GODOT_CPPIA}../../godot-cpp/gdextension/" />
		<compilerflag value="-I${GODOT_CPPIA}../../godot-cpp/include/" />
		<compilerflag value="-I${GODOT_CPPIA}../../godot-cpp/gen/include/" />
		<compilerflag value="-I${GODOT_CPPIA}cpp" />

		<file name="${GODOT_CPPIA}cpp/haxe_callable_custom.cpp" />

	</files>

	<files id="haxe">
		<compilerflag value="-I${GODOT_CPPIA}../../godot-cpp/gdextension/" />
		<compilerflag value="-I${GODOT_CPPIA}../../godot-cpp/include/" />
		<compilerflag value="-I${GODOT_CPPIA}../../godot-cpp/gen/include/" />
		<compilerflag value="-I${GODOT_CPPIA}cpp" />

		<file name="${GODOT_CPPIA}cpp/haxe_callable_custom.cpp" />
	</files>


</xml>