name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: macos-13

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Cache hxcpp
        uses: actions/cache@v4
        with:
          path: haxe/bin/**/*.o
          key: hxcpp-${{ runner.os }}

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.0-beta3
          use-dotnet: false

      - name: Install Lix
        uses: lix-pm/setup-lix@master

      - name: Install Haxe
        run: lix install haxe 4.3.6 --global

      - name: Install Haxe Libraries
        run: haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
      - run: yes | haxelib run hxcpp

      - run: python -m pip install scons
      - run: scons use_hot_reload=no generate_template_get_node=no build_library=no
        working-directory: godot-cpp

      - run: haxe --cwd haxe build.hxml
      - run: lipo -create -output haxe/bin/libcppia.a haxe/bin/libcppia_arm64-debug.a haxe/bin/libcppia_x86_64-debug.a
      - run: ls -lah haxe/bin
      # - run: mv haxe/bin/libcppia_x86_64-debug.a haxe/bin/libcppia.a

      - run: scons use_hot_reload=no generate_template_get_node=no debug_symbols=yes

      - run: ls -Lah test/bin
      # - run: nm -g test/bin/libgdcppia.linux.template_debug.x86_64.so
      # - run: ldd test/bin/libgdcppia.linux.template_debug.x86_64.so

      - run: godot --headless --verbose --import test/project.godot
      - run: godot --headless --verbose --path test main.tscn
