name: CI

on:
  push:
  pull_request:
    branches: [master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Install Lix
        uses: lix-pm/setup-lix@master

      - name: Install Haxe
        run: lix install haxe 4.3.6 --global

      - name: Install Haxe Libraries
        run: haxelib git hxcpp https://github.com/HaxeFoundation/hxcpp
      - run: yes | haxelib run hxcpp

      - run: python -m pip install scons
      - run: scons use_hot_reload=no generate_template_get_node=no
      - name: Build
        run: haxe --cwd haxe build.hxml
